#############################################################################
# Makefile for building: groove
# Generated by qmake (2.01a) (Qt 4.6.2) on: Tue Jul 20 16:35:58 2010
# Project:  Groove.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Groove.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DDATADIR="/usr/share" -DPKGDATADIR="" -DQT_PHONON_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtDBus -I/usr/include/qt4/phonon -I/usr/include/qt4 -I. -I/usr/include/qjson -I/usr/include/qt4/phonon_compat -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/local/lib -lqjson -lphonon -lQtDBus -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		groove.cpp \
		gscom.cpp \
		splayer.cpp \
		streamio.cpp \
		playlist.cpp \
		downloadmanager.cpp \
		grooveprogressbar.cpp \
		topbar.cpp \
		bottombar.cpp \
		vkb.cpp \
		searchresults.cpp moc_groove.cpp \
		moc_gscom.cpp \
		moc_splayer.cpp \
		moc_streamio.cpp \
		moc_playlist.cpp \
		moc_downloadmanager.cpp \
		moc_grooveprogressbar.cpp \
		moc_topbar.cpp \
		moc_bottombar.cpp \
		moc_vkb.cpp \
		moc_searchresults.cpp \
		qrc_res.cpp
OBJECTS       = main.o \
		groove.o \
		gscom.o \
		splayer.o \
		streamio.o \
		playlist.o \
		downloadmanager.o \
		grooveprogressbar.o \
		topbar.o \
		bottombar.o \
		vkb.o \
		searchresults.o \
		moc_groove.o \
		moc_gscom.o \
		moc_splayer.o \
		moc_streamio.o \
		moc_playlist.o \
		moc_downloadmanager.o \
		moc_grooveprogressbar.o \
		moc_topbar.o \
		moc_bottombar.o \
		moc_vkb.o \
		moc_searchresults.o \
		qrc_res.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Groove.pro
QMAKE_TARGET  = groove
DESTDIR       = 
TARGET        = groove

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_topbar.h ui_bottombar.h ui_vkb.h ui_searchresults.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Groove.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libphonon.prl \
		/usr/lib/libQtDBus.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Groove.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libphonon.prl:
/usr/lib/libQtDBus.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Groove.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/groove1.0.0 || $(MKDIR) .tmp/groove1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/groove1.0.0/ && $(COPY_FILE) --parents groove.h gscom.h splayer.h streamio.h playlist.h downloadmanager.h grooveprogressbar.h topbar.h bottombar.h vkb.h searchresults.h .tmp/groove1.0.0/ && $(COPY_FILE) --parents res.qrc .tmp/groove1.0.0/ && $(COPY_FILE) --parents main.cpp groove.cpp gscom.cpp splayer.cpp streamio.cpp playlist.cpp downloadmanager.cpp grooveprogressbar.cpp topbar.cpp bottombar.cpp vkb.cpp searchresults.cpp .tmp/groove1.0.0/ && $(COPY_FILE) --parents topbar.ui bottombar.ui vkb.ui searchresults.ui .tmp/groove1.0.0/ && (cd `dirname .tmp/groove1.0.0` && $(TAR) groove1.0.0.tar groove1.0.0 && $(COMPRESS) groove1.0.0.tar) && $(MOVE) `dirname .tmp/groove1.0.0`/groove1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/groove1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_groove.cpp moc_gscom.cpp moc_splayer.cpp moc_streamio.cpp moc_playlist.cpp moc_downloadmanager.cpp moc_grooveprogressbar.cpp moc_topbar.cpp moc_bottombar.cpp moc_vkb.cpp moc_searchresults.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_groove.cpp moc_gscom.cpp moc_splayer.cpp moc_streamio.cpp moc_playlist.cpp moc_downloadmanager.cpp moc_grooveprogressbar.cpp moc_topbar.cpp moc_bottombar.cpp moc_vkb.cpp moc_searchresults.cpp
moc_groove.cpp: gscom.h \
		splayer.h \
		streamio.h \
		grooveprogressbar.h \
		qmaemo5rotator.h \
		playlist.h \
		topbar.h \
		vkb.h \
		groove.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) groove.h -o moc_groove.cpp

moc_gscom.cpp: gscom.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gscom.h -o moc_gscom.cpp

moc_splayer.cpp: streamio.h \
		splayer.h \
		grooveprogressbar.h \
		qmaemo5rotator.h \
		playlist.h \
		gscom.h \
		splayer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) splayer.h -o moc_splayer.cpp

moc_streamio.cpp: splayer.h \
		streamio.h \
		grooveprogressbar.h \
		qmaemo5rotator.h \
		playlist.h \
		gscom.h \
		streamio.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) streamio.h -o moc_streamio.cpp

moc_playlist.cpp: gscom.h \
		playlist.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) playlist.h -o moc_playlist.cpp

moc_downloadmanager.cpp: downloadmanager.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) downloadmanager.h -o moc_downloadmanager.cpp

moc_grooveprogressbar.cpp: qmaemo5rotator.h \
		grooveprogressbar.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) grooveprogressbar.h -o moc_grooveprogressbar.cpp

moc_topbar.cpp: vkb.h \
		topbar.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) topbar.h -o moc_topbar.cpp

moc_bottombar.cpp: bottombar.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) bottombar.h -o moc_bottombar.cpp

moc_vkb.cpp: vkb.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) vkb.h -o moc_vkb.cpp

moc_searchresults.cpp: searchresults.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) searchresults.h -o moc_searchresults.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		general_fullsize.png \
		wmTaskModified.png \
		groove.png \
		general_search.png \
		general_add.png \
		wmTaskSwitcherIconPressed.png \
		camera_camera_setting.png \
		general_forward.png \
		camera_video_pause.png \
		general_close.png \
		general_foldertree.png \
		camera_video_stop.png \
		wmTaskSwitcherIcon.png \
		general_back.png \
		wmTaskSwitcherIconHighlight.png
	/usr/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all: ui_topbar.h ui_bottombar.h ui_vkb.h ui_searchresults.h
compiler_uic_clean:
	-$(DEL_FILE) ui_topbar.h ui_bottombar.h ui_vkb.h ui_searchresults.h
ui_topbar.h: topbar.ui
	/usr/bin/uic-qt4 topbar.ui -o ui_topbar.h

ui_bottombar.h: bottombar.ui
	/usr/bin/uic-qt4 bottombar.ui -o ui_bottombar.h

ui_vkb.h: vkb.ui
	/usr/bin/uic-qt4 vkb.ui -o ui_vkb.h

ui_searchresults.h: searchresults.ui
	/usr/bin/uic-qt4 searchresults.ui -o ui_searchresults.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp groove.h \
		gscom.h \
		splayer.h \
		streamio.h \
		grooveprogressbar.h \
		qmaemo5rotator.h \
		playlist.h \
		topbar.h \
		vkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

groove.o: groove.cpp groove.h \
		gscom.h \
		splayer.h \
		streamio.h \
		grooveprogressbar.h \
		qmaemo5rotator.h \
		playlist.h \
		topbar.h \
		vkb.h \
		bottombar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o groove.o groove.cpp

gscom.o: gscom.cpp gscom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gscom.o gscom.cpp

splayer.o: splayer.cpp splayer.h \
		streamio.h \
		grooveprogressbar.h \
		qmaemo5rotator.h \
		playlist.h \
		gscom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o splayer.o splayer.cpp

streamio.o: streamio.cpp streamio.h \
		splayer.h \
		grooveprogressbar.h \
		qmaemo5rotator.h \
		playlist.h \
		gscom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o streamio.o streamio.cpp

playlist.o: playlist.cpp playlist.h \
		gscom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playlist.o playlist.cpp

downloadmanager.o: downloadmanager.cpp downloadmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o downloadmanager.o downloadmanager.cpp

grooveprogressbar.o: grooveprogressbar.cpp grooveprogressbar.h \
		qmaemo5rotator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grooveprogressbar.o grooveprogressbar.cpp

topbar.o: topbar.cpp topbar.h \
		vkb.h \
		ui_topbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o topbar.o topbar.cpp

bottombar.o: bottombar.cpp bottombar.h \
		ui_bottombar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bottombar.o bottombar.cpp

vkb.o: vkb.cpp vkb.h \
		ui_vkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vkb.o vkb.cpp

searchresults.o: searchresults.cpp searchresults.h \
		ui_searchresults.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o searchresults.o searchresults.cpp

moc_groove.o: moc_groove.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_groove.o moc_groove.cpp

moc_gscom.o: moc_gscom.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gscom.o moc_gscom.cpp

moc_splayer.o: moc_splayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_splayer.o moc_splayer.cpp

moc_streamio.o: moc_streamio.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_streamio.o moc_streamio.cpp

moc_playlist.o: moc_playlist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_playlist.o moc_playlist.cpp

moc_downloadmanager.o: moc_downloadmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_downloadmanager.o moc_downloadmanager.cpp

moc_grooveprogressbar.o: moc_grooveprogressbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_grooveprogressbar.o moc_grooveprogressbar.cpp

moc_topbar.o: moc_topbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_topbar.o moc_topbar.cpp

moc_bottombar.o: moc_bottombar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bottombar.o moc_bottombar.cpp

moc_vkb.o: moc_vkb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vkb.o moc_vkb.cpp

moc_searchresults.o: moc_searchresults.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_searchresults.o moc_searchresults.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_desktop: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/hildon/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/hildon/ 
	-$(INSTALL_FILE) /scratchbox/users/eli/home/eli/qt4/Groove/groove.desktop $(INSTALL_ROOT)/usr/share/applications/hildon/


uninstall_desktop:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/hildon/groove.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/hildon/ 


install_icon64: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/ 
	-$(INSTALL_FILE) /scratchbox/users/eli/home/eli/qt4/Groove/groove.png $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/


uninstall_icon64:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/groove.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/ 


install:  install_target install_desktop install_icon64  FORCE

uninstall: uninstall_target uninstall_desktop uninstall_icon64   FORCE

FORCE:

