Document: groove
Title: Debian groove Manual
Author: <insert document author here>
Abstract: This manual describes what groove is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/groove/groove.sgml.gz

Format: postscript
Files: /usr/share/doc/groove/groove.ps.gz

Format: text
Files: /usr/share/doc/groove/groove.text.gz

Format: HTML
Index: /usr/share/doc/groove/html/index.html
Files: /usr/share/doc/groove/html/*.html
